=== tcofoegbu/bjs-template/biojsonschema.json
{"$schema":"http://json-schema.org/draft-04/schema#","id":"http://jsonschema.net","type":"object","properties":{"seqs":{"id":"http://jsonschema.net/seqs","type":"array","items":{"id":"http://jsonschema.net/seqs/0","type":"object","properties":{"name":{"id":"http://jsonschema.net/seqs/0/name","type":"string","description":"Sequence name"},"start":{"id":"http://jsonschema.net/seqs/0/start","type":"integer","description":"Start residue position"},"svid":{"id":"http://jsonschema.net/seqs/0/svid","type":"string","description":"Serial version id for sequence object"},"end":{"id":"http://jsonschema.net/seqs/0/end","type":"integer","description":"End residue position"},"id":{"id":"http://jsonschema.net/seqs/0/id","type":"string","description":"Sequence unique identifier"},"seq":{"id":"http://jsonschema.net/seqs/0/seq","type":"string","description":"Sequence Residues"},"order":{"id":"http://jsonschema.net/seqs/0/order","type":"integer","description":"Sequence order in an alignment space"}},"required":["name","start","svid","end","id","seq"]},"required":["0"],"description":"Sequences in the Alignemnt","minItems":"1","maxItems":"*"},"appSettings":{"id":"http://jsonschema.net/appSettings","type":"object","properties":{"globalColorScheme":{"id":"http://jsonschema.net/appSettings/globalColorScheme","type":"string","description":"Global colour schem for the alignment"},"webStartUrl":{"id":"http://jsonschema.net/appSettings/webStartUrl","type":"string","description":"Jalview specific setting which points to a url for launching Jalview"},"application":{"id":"http://jsonschema.net/appSettings/application","type":"string","description":"Application which generated the Json"},"showSeqFeatures":{"id":"http://jsonschema.net/appSettings/showSeqFeatures","type":"string","description":"Determines if sequence features are visible or not"},"version":{"id":"http://jsonschema.net/appSettings/version","type":"string","description":"Verion of the application which generated the JSON"},"hiddenCols":{"id":"http://jsonschema.net/appSettings/hiddenCols","type":"string","description":"Delimited lists of hidden colums ranges i.e [2-3,5-5,11-23]"}},"description":"Application specific settings"},"seqGroups":{"id":"http://jsonschema.net/seqGroups","type":"array","items":[{"id":"http://jsonschema.net/seqGroups/0","type":"object","properties":{"displayText":{"id":"http://jsonschema.net/seqGroups/0/displayText","type":"boolean","description":"Determines if the texts of the group is displayed or not"},"startRes":{"id":"http://jsonschema.net/seqGroups/0/startRes","type":"integer","description":"Start residue position for a given group"},"groupName":{"id":"http://jsonschema.net/seqGroups/0/groupName","type":"string","description":"Group name"},"endRes":{"id":"http://jsonschema.net/seqGroups/0/endRes","type":"integer","description":"End residue position for a given group"},"colourText":{"id":"http://jsonschema.net/seqGroups/0/colourText","type":"boolean","description":"Determines if the Residues text for the group is coloured"},"seqsHash":{"id":"http://jsonschema.net/seqGroups/0/seqsHash","type":"array","items":[],"minItems":"0","maxItems":"*","description":"The id's of the sequences which belongs to the group"},"svid":{"id":"http://jsonschema.net/seqGroups/0/svid","type":"string","description":"Serial version id for a given group"},"showNonconserved":{"id":"http://jsonschema.net/seqGroups/0/showNonconserved","type":"boolean","description":"Determines if non conserved regions of a group is shown or not"},"colourScheme":{"id":"http://jsonschema.net/seqGroups/0/colourScheme","type":"string","description":"Colour Scheme for the sequence group"},"displayBoxes":{"id":"http://jsonschema.net/seqGroups/0/displayBoxes","type":"boolean","description":"Determines if the group border should be visible or not"}}}],"description":"Sequence groups in the Alignment","minItems":"0","maxItems":"*"},"alignAnnotation":{"id":"http://jsonschema.net/alignAnnotation","type":"array","items":{"id":"http://jsonschema.net/alignAnnotation/0","type":"object","properties":{"svid":{"id":"http://jsonschema.net/alignAnnotation/0/svid","type":"string","description":"Serial version id for the annotation object"},"annotations":{"id":"http://jsonschema.net/alignAnnotation/0/annotations","type":"array","items":[{"id":"http://jsonschema.net/alignAnnotation/0/annotations/0","type":"object","properties":{"displayCharacter":{"id":"http://jsonschema.net/alignAnnotation/0/annotations/0/displayCharacter","type":"string","description":"Display character to denote the given annotation"},"value":{"id":"http://jsonschema.net/alignAnnotation/0/annotations/0/value","type":"integer","description":"Value of the annotation"},"secondaryStructure":{"id":"http://jsonschema.net/alignAnnotation/0/annotations/0/secondaryStructure","type":"string","description":"Secondary structure symbol for the given annotation"}}},{"id":"http://jsonschema.net/alignAnnotation/0/annotations/1","type":"object","properties":{"displayCharacter":{"id":"http://jsonschema.net/alignAnnotation/0/annotations/1/displayCharacter","type":"string"},"value":{"id":"http://jsonschema.net/alignAnnotation/0/annotations/1/value","type":"integer"},"secondaryStructure":{"id":"http://jsonschema.net/alignAnnotation/0/annotations/1/secondaryStructure","type":"string"}}},{"id":"http://jsonschema.net/alignAnnotation/0/annotations/2","type":"object","properties":{"displayCharacter":{"id":"http://jsonschema.net/alignAnnotation/0/annotations/2/displayCharacter","type":"string"},"value":{"id":"http://jsonschema.net/alignAnnotation/0/annotations/2/value","type":"integer"},"secondaryStructure":{"id":"http://jsonschema.net/alignAnnotation/0/annotations/2/secondaryStructure","type":"string"}}}]},"description":{"id":"http://jsonschema.net/alignAnnotation/0/description","type":"string","description":"Description of the Alignment Annotation"},"label":{"id":"http://jsonschema.net/alignAnnotation/0/label","type":"string","description":"Label for the Annotation"}}},"description":"Alignment Annotations","minItems":"0","maxItems":"*"},"svid":{"id":"http://jsonschema.net/svid","type":"string","description":"Serial version id"},"seqFeatures":{"id":"http://jsonschema.net/seqFeatures","type":"array","items":{"id":"http://jsonschema.net/seqFeatures/0","type":"object","properties":{"fillColor":{"id":"http://jsonschema.net/seqFeatures/0/fillColor","type":"string","description":"Fill colour"},"score":{"id":"http://jsonschema.net/seqFeatures/0/score","type":"integer","description":"Score"},"sequenceRef":{"id":"http://jsonschema.net/seqFeatures/0/sequenceRef","type":"string","description":"Reference to the Sequence in the alignement (More like a foreign key)"},"featureGroup":{"id":"http://jsonschema.net/seqFeatures/0/featureGroup","type":"string","description":"Feature Group"},"svid":{"id":"http://jsonschema.net/seqFeatures/0/svid","type":"string","description":"Serial version id for the SeqFeature object"},"description":{"id":"http://jsonschema.net/seqFeatures/0/description","type":"string","description":"Description of Feature"},"xStart":{"id":"http://jsonschema.net/seqFeatures/0/xStart","type":"integer","description":"Start residue position for the sequence feature"},"xEnd":{"id":"http://jsonschema.net/seqFeatures/0/xEnd","type":"integer","description":"End residue position for the sequence feature"},"type":{"id":"http://jsonschema.net/seqFeatures/0/type","type":"string","description":"The name of the SequenceFeature"}}},"minItems":"0","maxItems":"*","description":"Sequence Features within the alignment"}},"required":["seqs","appSettings","seqGroups","alignAnnotation","svid","seqFeatures"]}

=== tcofoegbu/bjs-template/example_biojsons.json
{
    "seqs": [
        {
            "name": "FER_CAPAN/125-135",
            "start": 125,
            "svid": "1.0",
            "end": 135,
            "id": "1841182323",
            "seq": "VAYPQSDVTIE",
            "order": 1
        },
        {
            "name": "FER1_SOLLC/125-135",
            "start": 125,
            "svid": "1.0",
            "end": 135,
            "id": "1827803677",
            "seq": "VAYPKGDVTIE",
            "order": 2
        },
        {
            "name": "Q93XJ9_SOLTU/125-135",
            "start": 125,
            "svid": "1.0",
            "end": 135,
            "id": "246218698",
            "seq": "VAYPKCDVTIE",
            "order": 3
        },
        {
            "name": "FER1_PEA/130-140",
            "start": 130,
            "svid": "1.0",
            "end": 140,
            "id": "320593394",
            "seq": "VAYPTSDVVIE",
            "order": 4
        },
        {
            "name": "Q7XA98_TRIPR/133-143",
            "start": 133,
            "svid": "1.0",
            "end": 143,
            "id": "252345420",
            "seq": "VAFPTSDVTIE",
            "order": 5
        }
    ],
    "seqGroups": [
        {
            "displayText": true,
            "startRes": 2,
            "groupName": "JGroup:48822124",
            "endRes": 4,
            "colourText": false,
            "seqsHash": [
                "1841182323",
                "246218698"
            ],
            "svid": "1.0",
            "showNonconserved": false,
            "colourScheme": "Zappo",
            "displayBoxes": true
        }
    ],
    "alignAnnotation": [
        {
            "svid": "1.0",
            "annotations": [
                {
                    "displayCharacter": "",
                    "value": 0,
                    "secondaryStructure": "\u0000"
                },
                {
                    "displayCharacter": "",
                    "value": 0,
                    "secondaryStructure": "\u0000"
                },
                {
                    "displayCharacter": "",
                    "value": 0,
                    "secondaryStructure": "\u0000"
                },
                {
                    "description": "",
                    "displayCharacter": "β",
                    "value": 0,
                    "secondaryStructure": "E"
                },
                {
                    "description": "",
                    "displayCharacter": "β",
                    "value": 0,
                    "secondaryStructure": "E"
                },
                {
                    "displayCharacter": "",
                    "value": 0,
                    "secondaryStructure": "\u0000"
                },
                {
                    "description": "",
                    "displayCharacter": "α",
                    "value": 0,
                    "secondaryStructure": "H"
                },
                {
                    "description": "",
                    "displayCharacter": "α",
                    "value": 0,
                    "secondaryStructure": "H"
                },
                {
                    "displayCharacter": "",
                    "value": 0,
                    "secondaryStructure": "\u0000"
                },
                {
                    "displayCharacter": "",
                    "value": 0,
                    "secondaryStructure": "\u0000"
                },
                {
                    "displayCharacter": "",
                    "value": 0,
                    "secondaryStructure": "\u0000"
                }
            ],
            "description": "Secondary Structure",
            "label": "Secondary Structure"
        }
    ],
    "seqFeatures": [
        {
            "fillColor": "#c13516",
            "score": 0,
            "sequenceRef": "246218698",
            "featureGroup": "Jalview",
            "svid": "1.0",
            "description": "feature description",
            "xStart": 5,
            "xEnd": 9,
            "type": "feature"
        },
        {
            "fillColor": "#c13516",
            "score": 0,
            "sequenceRef": "320593394",
            "featureGroup": "Jalview",
            "svid": "1.0",
            "description": "feature description",
            "xStart": 5,
            "xEnd": 9,
            "type": "feature"
        },
        {
            "fillColor": "#c13516",
            "score": 0,
            "sequenceRef": "252345420",
            "featureGroup": "Jalview",
            "svid": "1.0",
            "description": "feature description",
            "xStart": 5,
            "xEnd": 9,
            "type": "feature"
        }
    ],
    "appSettings": {
        "globalColorScheme": "foo",
        "webStartUrl": "www.jalview.org/services/launchApp",
        "application": "Jalview",
        "hiddenSeqs": "1827803677",
        "showSeqFeatures": "true",
        "version": "2.9",
        "hiddenCols": "0-0;10-10"
    },
    "svid": "1.0"
}
